# Generated by Django 2.2.1 on 2019-05-05 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('rank', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weaponry', models.CharField(max_length=200)),
                ('payload', models.IntegerField(default=0)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetdata.Pilot')),
            ],
        ),
        migrations.CreateModel(
            name='StarshipAttribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetdata.Starship')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('coordinates', models.CharField(max_length=200)),
                ('hangar_size', models.IntegerField(default=0)),
                ('is_military', models.BooleanField(default=False)),
                ('attributed_starships', models.ManyToManyField(through='fleetdata.StarshipAttribution', to='fleetdata.Starship')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetdata.Pilot')),
            ],
        ),
        migrations.AddField(
            model_name='starshipattribution',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetdata.Station'),
        ),
        migrations.AddField(
            model_name='pilot',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetdata.Race'),
        ),
        migrations.CreateModel(
            name='FleetAttribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetdata.Fleet')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetdata.Station')),
            ],
        ),
        migrations.AddField(
            model_name='fleet',
            name='chief',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetdata.Pilot'),
        ),
        migrations.AddField(
            model_name='fleet',
            name='main_race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetdata.Race'),
        ),
        migrations.AddField(
            model_name='fleet',
            name='stations',
            field=models.ManyToManyField(through='fleetdata.FleetAttribution', to='fleetdata.Station'),
        ),
    ]
